### ISSUE TITLE
Haksız yere ban

### ISSUE THREAD

**Issue by Crazybekirtr** [UnioDex/UnioCraft#1]
Lütfen banımı açın çeşitli yerlerden ve facebbok gruplarından mesaj yolladım Haksız olsamda bukadar uğraş sonucu açmanız gerekir diye düşünüyorum ve yaklaşık 10 aydır bu serverde oynuyorum 10 a yakın videom var Nick: CrazyBekirTR  Yiğit abi badlion serverinde bile adamlar adminlerle iletişim kurunca açıyolar banlanmda nedenim ise soloda team olmak oysaki ben olmadım olduysamda özür dilerim banımı açın lütfen şimdiden teşekkürler

**Comment by Wolfchanze** [comment]
Hangi bölümde ban yediğini söylermisin ?

**Comment by ygtdmn** [comment]
GitHub teknik sorunlar için açıldı. Bu tür konuları www.uniocraft.com/iletisim.php adresinden iletin. Ancak yine de söylemeliyim ki genellikle ban kaldırmıyoruz.
